name: Build and tests firmware
on:
  push:
    branches:
      - master
      - hotfix/*

env:
  RUN_ID: github-actions-${{ github.run_number }}

jobs:
  build-firmware:
    name: Build Firmware
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'chore:')"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y wget flex bison gperf python3-pip python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0
      - name: Prepare ESP-IDF environment
        run: make prepare
      - name: Build firmware for ESP32-S3 
        run: make build TARGET=esp32s3
      - name: Build firmware for Emulator
        run: make build-emulator
      - name: Get new version
        run: python3 scripts/ci/bump_version.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create and push git tag
        run: |
          git config --local user.name 'Github Action'
          git config --local user.email 'github-action@users.noreply.github.com'
          git tag $VERSION
          git push --tags
