name: Release Firmware
run-name: Release Firmware ${{ inputs.version }}
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (vX.Y.Z)'
        required: true
        type: string

jobs:
  publish-application:
    name: Publish application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.version }}
          submodules: "recursive"
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y wget flex bison gperf python3-pip python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0
      - name: Prepare ESP-IDF environment
        run: make prepare    
      - name: Build firmware for ESP32-S3 
        run: make build TARGET=esp32s3
      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware-output
          path: |
            build/*.bin
            build/*.elf
            build/*.map
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Firmware ${{ inputs.version }}
          tag_name: ${{ inputs.version }}
          files: |
            build/*.bin
            build/*.elf
            build/*.map
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}